apiVersion: v1
clusters:
- name: "cluster"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1ERXhNREl4TkRNd05Gb1hEVE0wTURFeE1ESXhORE13TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSzF5ClNBdXFzSUljSC82WlpnK1NzOURWQU1ITFR0ejVaTE12cHY1K2xuclhOcCtjV2dqNXk2dE40SXphTHNwemtlSU8KZC9UamVZNStDdnZXNlRzQSs3RVJ3SXllY0tJYkd0L2lpa2ZIZFRMTmZBellpUlVqZjhZc0JVYVlWMjc0bUUwMgpCcW1qeGlrVkJ5UEtDZlJGTUdnSEJqUDI1SVJQMUVhVmFVaDVKU3IrajlIa3A5b21NZW10aUhYN3hEM3k5TWh5CkZ3aEdBK0ZEcmhlQkIzK1VLUVU1ZjIxYXNXeWRNbkZ5eWFzUHZ6WDVzWkg5emdWSXFQTkVySXNSbmJZcDRaN0cKdi9tUEtJNWxBcEsweG53ek92cTc1K1BpVzZZcTNYZy9JTmFnbG9wa2w5RkMyVXYzblhIUHNVNWRpOU0zL2VjaQpaaE80WlJqaVUrWjk1ZjRrTHprQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZLNTdDZ0t6Q2pLZCttUytWL0g0d2NwbUl1RG9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBVXIybEZuWVI2Wk0vMTd6WnF1NjBLMTRPUVoxV3ZrSmJmcXJFaFhEd08vQzJTck13UAprS2s4MFc5ZVVZWXl2T2grSjZMbVRGcTVxbitnK09mazFHak5zTkRqZlhZbzE0TkVDcG1xWTVmUktQaHpIYjR4CkwxbUFKbVdaMTZQZ29uWEtVQkt1c3pjZGpXeUE2RWI5MnV3U1ZwQUV0blNSM1ExUWFsT2xtWFdEclUrR2IxcjMKRHZmUE1mait6Snh3RGM2R0U3M2tZVXgvVTJYd3NFSlF5UlpLYkNTdndTTWFiRkZxZDVBcGwrZU9LU1JGRkw2RgpnSGtJZG5vRHhhZzRVTGs3dCtwMG15Y0h0Zkp5Tkc0RHNWbkpyVnBBN2RuZXNUeGVIRVBDdDFpTmY2STY4c1ZMCkhqejI3aWRTY3Z3cHlsbC9pOXkzcVV0b3RvL0s5NVVKL01GNAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://bd993513-3cfd-4562-b01e-e415834e94ea.api.k8s.fr-par.scw.cloud:6443
contexts:
- name: admin@cluster
  context:
    cluster: "cluster"
    user: cluster-admin
current-context: admin@cluster
kind: Config
preferences: {}
users:
- name: cluster-admin
  user:
    token: mMRZd9CILMa8ElM8kkWt7r5aeVHw7OGP5mp3mdVqmWqrlH1QO5VGPXPM
